### ISSUE TITLE
Remove Compass dependency?

### ISSUE THREAD

**Issue by naevtamarkus** [coskuntekin/middleman_starter_kit#1]
Hi,

As you may know, Compass is not being supported any longer. Could you please give me a hint on how to remove the Compass dependency from this kit?
I'm getting some warnings from Compass and would also like to keep my site more lightweight by removing unwanted components.

Thanks!

**Comment by coskuntekin** [comment]
@naevtamarkus i removed would you review?

**Comment by naevtamarkus** [comment]
Sure!
